name: 'Setup Node.js environment'
description: 'Installs node 20 and fetched pnpm cache, then runs pnpm install'
author: 'leon'
inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 20.x, 20.4.0, >=20.0.0'
    default: '22'
  cache-key:
    description: 'A key to use for the cache. sometimes you need to bust the cache'
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Enable NPM Corepack
      shell: bash
      run: npm install -g corepack

    - name: Use node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
